apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-auto-update-geojson-config
  namespace: osm
data:
  mein_europa.geojson: |
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
           [7.0, 56.0],
           [10.0, 56.0],
           [13.5, 55.8],
           [15.8, 55.2],
           [16.2, 53.5],
           [16.5, 52.0],
           [16.2, 50.0],
           [18.0, 49.5],
           [18.0, 48.0],
           [14.5, 47.5],
           [13.0, 46.5],
           [10.0, 46.2],
           [7.8, 46.5],
           [6.2, 47.2],
           [5.0, 48.5],
           [4.2, 49.8],
           [4.0, 51.5],
           [4.8, 53.8],
           [7.0, 56.0]
          ]
        ]
      }
    }
  japan.geojson: |
    {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "properties": {},
          "geometry": {
            "type": "Polygon",
            "coordinates": [
              [
                [
                  128.5,
                  31
                ],
                [
                  129,
                  34.8
                ],
                [
                  132,
                  36.5
                ],
                [
                  136,
                  38
                ],
                [
                  139.5,
                  43
                ],
                [
                  141.5,
                  46.2
                ],
                [
                  147.2,
                  44.5
                ],
                [
                  142.5,
                  38
                ],
                [
                  141.5,
                  35.5
                ],
                [
                  139,
                  34
                ],
                [
                  135.5,
                  33
                ],
                [
                  132.5,
                  32.2
                ],
                [
                  130.5,
                  30.5
                ],
                [
                  128.5,
                  31
                ]
              ]
            ]
          }
        }
      ]
    }
  privat.osm: |
    <?xml version='1.0' encoding='UTF-8'?>
    <osm version="0.6" generator="Local POI Script">
    <node id="991785489750" lat="51.5816327" lon="6.729971531333579">
        <tag k="name" v="Homeoffice Holger" />
        <tag k="tourism" v="attraction" />
      </node>
    </osm>
