apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-auto-update-filter-config
  namespace: osm
data:
  welt_filter.txt: |
    n/place=country,state,region,city,ocean,sea
    r/boundary=administrative+admin_level=1,2,3,4
    n/natural=ocean,sea
    w/natural=ocean,sea
    r/natural=ocean,sea
    w/waterway=river
    r/waterway=river
    n/waterway=river
    n/tourism=theme_park
    w/tourism=theme_park
    r/tourism=theme_park
    w/highway=motorway,motorway_link
    n/highway=motorway_junction
    n/construction=theme_park
    w/construction=theme_park
    r/construction=theme_park
    
