apiVersion: v1
kind: Namespace
metadata:
  name: osm

---
apiVersion: v1
kind: LimitRange
metadata:
  name: osm
  namespace: osm
spec:
  limits:
    - type: Container
      # Standard-Zuweisungen (Requests), wenn im Pod-YAML gar nichts eingetragen ist:
      defaultRequest:
        cpu: "0.1"
        memory: "2Gi"
      # Standard-Grenzwerte (Limits), die automatisch gesetzt werden:
      default:
        cpu: "8"
        memory: "12Gi"