apiVersion: v1
kind: Service
metadata:
  name: valhalla-blue
  namespace: osm
  labels:
    app: valhalla
    color: blue
spec:
  type: NodePort
  selector:
    app: valhalla
    color: blue
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      nodePort: 31089
