apiVersion: apps/v1
kind: Deployment
metadata:
  name: nominatim
  namespace: osm
  labels:
    app: nominatim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nominatim
  template:
    metadata:
      labels:
        app: nominatim
    spec:
      containers:
        - name: nominatim
          image: mediagis/nominatim:4.5
          imagePullPolicy: IfNotPresent
          env:
            - name: PBF_PATH
              value: /nominatim/data/import/planet.osm.pbf
            - name: NOMINATIM_PASSWORD
              value: nominatim
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nominatim-data
              mountPath: /var/lib/postgresql/15/main
            - name: import-data
              mountPath: /nominatim/data/import
              readOnly: true
      volumes:
        - name: nominatim-data
          hostPath:
            path: /mnt/data/OSM/nominatim
            type: DirectoryOrCreate
        - name: import-data
          hostPath:
            path: /mnt/data/OSM/import
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nominatim
  namespace: osm
spec:
  type: NodePort
  selector:
    app: nominatim
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081
