apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-pelias-config
  namespace: osm
data:
  runtime-pelias.json: |
    {
      "logger": {
        "level": "info",
        "timestamp": false
      },
      "esclient": {
        "apiVersion": "7.5",
        "hosts": [
          {
            "host": "127.0.0.1",
            "port": 9200,
            "protocol": "http"
          }
        ]
      },
      "schema": {
        "indexName": "pelias"
      },
      "api": {
        "indexName": "pelias"
      }
    }
  import-pelias-template.json: |
    {
      "logger": {
        "level": "info",
        "timestamp": false
      },
      "esclient": {
        "apiVersion": "7.5",
        "hosts": [
          {
            "host": "pelias-elasticsearch.osm.svc.cluster.local",
            "port": 9200,
            "protocol": "http"
          }
        ]
      },
      "schema": {
        "indexName": "__PELIAS_INDEX__"
      },
      "api": {
        "indexName": "__PELIAS_INDEX__"
      },
      "imports": {
        "adminLookup": {
          "enabled": false
        },
        "openstreetmap": {
          "datapath": "/osm-temp/pelias/work/openstreetmap",
          "leveldbpath": "/osm-temp/pelias/work/leveldb",
          "import": [
            {
              "filename": "__PELIAS_PBF_FILE__"
            }
          ]
        }
      }
    }
