apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-pelias-config
  namespace: osm
data:
  pbf-root: /planet
  pbf-file: europa.osm.pbf
  temp-root: /osm-temp/pelias
  # Used by the Pelias import job, which runs in a separate pod.
  elasticsearch-host: pelias-elasticsearch.osm.svc.cluster.local
  runtime-pelias.json: |
    {
      "logger": {
        "level": "info",
        "timestamp": false
      },
      "esclient": {
        "apiVersion": "7.17",
        "hosts": [
          {
            "host": "127.0.0.1",
            "port": 9200,
            "protocol": "http"
          }
        ]
      },
      "schema": {
        "indexName": "pelias"
      },
      "api": {
        "indexName": "pelias"
      }
    }
  import-pelias-template.json: |
    {
      "logger": {
        "level": "info",
        "timestamp": false
      },
      "esclient": {
        "apiVersion": "7.17",
        "hosts": [
          {
            "host": "__PELIAS_ELASTICSEARCH_HOST__",
            "port": 9200,
            "protocol": "http"
          }
        ]
      },
      "schema": {
        "indexName": "__PELIAS_INDEX__"
      },
      "api": {
        "indexName": "__PELIAS_INDEX__"
      },
      "imports": {
        "adminLookup": {
          "enabled": false
        },
        "openstreetmap": {
          "datapath": "__PELIAS_TEMP_ROOT__/work/openstreetmap",
          "leveldbpath": "__PELIAS_TEMP_ROOT__/work/leveldb",
          "import": [
            {
              "filename": "__PELIAS_PBF_FILE__"
            }
          ]
        }
      }
    }
