apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: osm
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:16-3.4-alpine
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "16Gi"   # Garantiert der DB diesen Speicher
              cpu: "4"         # Garantiert 4 CPU-Kerne
            limits:
              memory: "20Gi"   # Maximaler Puffer für Spitzen (z.B. Index-Erstellung)
              cpu: "14"
          args:
            - "-c"
            - "shared_buffers=8GB"               # ~25% deines RAMs
            - "-c"
            - "maintenance_work_mem=8GB"         # Wichtig für Index-Erstellung beim Import
            - "-c"
            - "work_mem=64MB"
            - "-c"
            - "autovacuum_work_mem=2GB"
            - "-c"
            - "synchronous_commit=off"           # Riesiger Boost für Imports (Sicherheit egal beim Import)
            - "-c"
            - "max_wal_size=10GB"                # Größer ist besser, verhindert ständige Checkpoints
            - "-c"
            - "checkpoint_timeout=30min"
            - "-c"
            - "checkpoint_completion_target=0.9"
            - "-c"
            - "random_page_cost=2.1"             # 1.1 für SSDs, bei HDD eher 4.0 lassen
            - "-c"
            - "wal_level=minimal"
            - "-c"
            - "max_wal_senders=0"
          env:
            - name: POSTGRES_DB
              value: osm
            - name: POSTGRES_USER
              value: osm
            - name: POSTGRES_PASSWORD
              value: osm
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          hostPath:
            path: /mnt/data/OSM/postgres/data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: osm
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
