apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-status-config
  namespace: osm
data:
  config.json: |
    {
      "node_url": "",
      "auto_update_enabled": false,
      "auto_update_time": "03:00",
      "routing_costing_models": {
        "car": {"enabled": true},
        "foot": {"enabled": true},
        "bicycle": {"enabled": true}
      },
      "routing_speeds": {
        "car": 120,
        "foot": 5,
        "bicycle": 25
      },
      "routing_advanced": {
        "car": {"toll_factor": 1.0, "unpaved_factor": 1.0, "ferry_factor": 1.0},
        "foot": {"hill_factor": 1.0, "unpaved_factor": 1.0},
        "bicycle": {"hill_factor": 1.0, "unpaved_factor": 1.0}
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-service-targets
  namespace: osm
data:
  service-targets.json: |
    {
      "tileserver": "http://192.168.188.8:30085",
      "nominatim": "http://192.168.188.8:30081",
      "valhalla": "http://192.168.188.8:30082",
      "photon": "http://192.168.188.8:30087",
      "pelias": "http://192.168.188.8:30088",
      "web": "http://192.168.188.8:30084",
      "status": "http://status.osm.svc.cluster.local:8080"
    }
