apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-tileserver-import-profile-config
  namespace: osm
data:
  rollercoaster.yml: |
    # Erbt vollständig vom Standard-OpenMapTiles-Profil
    schema: openmaptiles

    # Ergänzungen/Add-ons zum bestehenden Profil
    layers:
      - name: transportation
        features:
          - source: osm
            geometry: line
            filter:
              - roller_coaster: track
            attributes:
              - key: class
                value: track
              - key: subclass
                value: roller_coaster
            min_zoom: 12
