apiVersion: v1
kind: ConfigMap
metadata:
  name: osm-valhalla-config
  namespace: osm
data:
  valhalla.json: |
    {
      "httpd": {
        "service": true,
        "listen": "0.0.0.0",
        "port": 8002
      },
      "loki": {
        "actions": ["route", "locate", "height"],
        "logging": true
      },
      "meili": {
        "mode": "std",
        "grid": {
          "cache_size": 100240
        },
        "default": true
      },
      "service_limits": {
        "auto": {
          "max_distance": 5000000.0,
          "max_locations": 20,
          "max_matrix_distance": 200000.0,
          "max_matrix_locations": 50
        },
        "pedestrian": {
          "max_distance": 5000000.0,
          "max_locations": 20
        },
        "bicycle": {
          "max_distance": 5000000.0,
          "max_locations": 20
        },
        "truck": {
          "max_distance": 5000000.0,
          "max_locations": 20
        }
      },
      "tiles": {
        "tile_dir": "/data/tiles"
      }
    }
