apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photon-green-pvc
  namespace: osm
  labels:
    app: photon
    color: green
    active: "true"
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 80Gi
