apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planet-storage-pvc
  namespace: osm
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 750Gi
