apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valhalla-green-pvc
  namespace: osm
  labels:
    app: valhalla
    color: green
    active: "true"
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
